### ISSUE TITLE
Force updater not working

### ISSUE THREAD

**Issue by daniel3xxx** [pal1000/Realtek-UAD-generic#10]
I tried the last 6.0.8783.1 but is not updating the driver, still on 6.0.8779.1 even after using force updater.

![1](https://user-images.githubusercontent.com/50595277/63557900-80be9d80-c542-11e9-98a1-5ee72d7586a2.png)

**Comment by pal1000** [comment]
Actually it worked as expected on your system. Force updater only updates the driver files. It is intended to workaround #9.  Because we lack proper INFs, force updater is the only option. Because the driver version can be obtained in multiple ways we get conflicting information. Some ways the driver version can be obtained include:
- locate and read sys file properties directly;
- look in registry;
- look in Windows driver store and execute the PNF files via pnputil or DISM.

Only the first method show correct results. Some tools use one or even more methods to get the version:

Device Manager
![force-update-expected-result-device-manager](https://user-images.githubusercontent.com/1138235/63579491-767cbd80-c59b-11e9-8f98-d0efe3ccfdc5.png)
Realtek Audio Console
![force-update-expected-result-realtek-audio-console](https://user-images.githubusercontent.com/1138235/63579605-b93e9580-c59b-11e9-8f81-cb00ed3d939e.png)
Driver Store explorer (RAPR)
![force-update-expected-result-RAPR](https://user-images.githubusercontent.com/1138235/63579670-d70bfa80-c59b-11e9-988a-d8e103ff8557.png)
Sysinternals Autoruns
![force-update-expected-result-autoruns](https://user-images.githubusercontent.com/1138235/63579717-f1de6f00-c59b-11e9-8005-d4c1760308c9.png)

**Comment by 29988122** [comment]
I think you should put this in the readme...

I myself personally reboot for like 4 times, before I got to read this closed issue.
Really confused by the version told by Device Manager.

Thanks!
