### ISSUE TITLE
it was working well then "can not connect to RPC service"

### ISSUE THREAD

**Issue by madakab** [pal1000/Realtek-UAD-generic#12]
Hello,
I hope you are doing well.
I wrote #6 before, and on that time, everything got fixed and worked well.
After a week or so I started to notice that the Console was sometimes working and others were giving this RPC error, at that time I tried to reinstall and that helped me by every time I get the error I install the latest version you release.
But today I got the error tried to install the same version and the current latest version, and it's still the same I'm still getting the same error.
I hope you can help me in solving this.
Attention: I didn't install any official version all are yours.

**Comment by pal1000** [comment]
Please post Driver store explorer screenshots so I can look if something is obviously wrong.

**Comment by madakab** [comment]
![image](https://user-images.githubusercontent.com/32437721/63636077-b2328880-c66a-11e9-847a-a26adef96f20.png)
![image](https://user-images.githubusercontent.com/32437721/63636090-c5455880-c66a-11e9-99ff-fff86ddf9d4b.png)

**Comment by pal1000** [comment]
I found both 6.0.8774.1 and 6.0.8783.1 drivers in your driver store. I don't know why the uninstall of driver version 6.0.8774.1 failed so bad. Maybe you used rollback driver feature or something, but we have to clean up the mess to get in the clear.

- Run Unofficial Realtek UAD generic setup until it asks you to install the new version. Respond with n so that it quits (uninstall only);
- Open Driver store explorer and perform delete operation on every remaining copy of `hdxrt.inf` from `Sound, video and game controllers` section, `hdx_genericext_rtk.inf` from `Extensions` section and `realtekhsa.inf`, `realtekapo.inf` and `realtekservice.inf` from `Software components` section. You shouldn't have to check force delete option in Driver store explorer but if some delete operations fail you'll have to;
- Open regedit and go to `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager` and look in right panel under Name column for `PendingFileRenameOperations`;
- if it does exist double click it and check if it contains a path under windows\system32 or windows\system32\drivers. If there is such content a reboot is required. Make sure you cut Internet connection before rebooting or Windows update will ruin your day with a new mess;
- Run Unofficial Realtek UAD generic setup again and this time let it install the driver.

Good luck.

**Comment by madakab** [comment]
![image](https://user-images.githubusercontent.com/32437721/63654165-e8f5c500-c776-11e9-9b54-8a35299c5046.png)
![image](https://user-images.githubusercontent.com/32437721/63654172-ff038580-c776-11e9-9869-2e235cb9f8ba.png)
the problem remains and I did everything you said but I didn't find the Reg "PendingFileRenameOperations"

**Comment by madakab** [comment]
UPDATE: I uninstalled V. 6.0.8783.1-2 and installed V. 6.0.8783.1 
And it worked. I think the problem is from the latest version.
I hope I don't get RPC error again because of no echo and noise cancellation on my mic when I get this error.

**Comment by pal1000** [comment]
With 6.0.8784.1 I was finally able to re-sync codec and extension versions fixing #9. These de-synced with 6,0.8783.1 and that may be the reason for your issue though it could be just a coincidence.
