### ISSUE TITLE
Headphones work after initially installing, but no longer work after restarting.

### ISSUE THREAD

**Issue by Jatts-Art** [pal1000/Realtek-UAD-generic#152]
I had recently put together a new PC and needed to install audio drivers. I came across this github because I wanted to install Realtek drivers without the Sonic crap included along with it. Following the guide, everything seemed to have ran smoothly.

However, a few days later, when plugging in my headsets I noticed there was no audio at all. After awhile of trying to solve it, I had decided to simply redo the audio driver installs, using the guide once again. Right after I had finished, the audio began working again on the headsets (and still worked on speakers when it was unplugged).

Unfortunately... after restarting the PC, the headsets immediately returned to not working once again. So I really have no idea what the deal is, and now I've come here for help. Using Windows 10.

**Comment by epman100** [comment]
> I had recently put together a new PC and needed to install audio drivers. I came across this github because I wanted to install Realtek drivers without the Sonic crap included along with it. Following the guide, everything seemed to have ran smoothly.

since you mentioned Sonic (possibly a reference to Sonic Studio), I assume you are using an Asus ROG motherboard or laptop as you **did not specify** what kind of system you are using, which makes it harder for people to help you out.

try using the original audio drivers first from asus rather than using any of the realtek uad generic drivers here and see if you get a different result or not.
