### ISSUE TITLE
Doesn't installs on windows 10 build 19033

### ISSUE THREAD

**Issue by gtumanyan** [pal1000/Realtek-UAD-generic#26]
HDAUDIO\FUNC_01&VEN_10EC&DEV_0889&SUBSYS_1458A022&REV_1000\4&36360A8E&0&0201: Disabled
1 device(s) disabled.

No matching devices found.

HDAUDIO\FUNC_01&VEN_10EC&DEV_0889&SUBSYS_1458A022&REV_1000\4&36360A8E&0&0201: Removed
1 device(s) were removed.

No devices were removed.
<->
Do you want to install unofficial and minimal Realtek UAD generic package (y/n):y

Microsoft PnP Utility

Adding driver package:  Win64\HDXRT.inf
Driver package added successfully.
Published Name:         oem0.inf

Adding driver package:  Win64\HDXRTSST.inf
Driver package added successfully.
Published Name:         oem7.inf

Adding driver package:  Win64\Realtek\ExtRtk_8824\HDX_GenericExt_RTK.inf
Driver package added successfully.
Published Name:         oem8.inf

Adding driver package:  Win64\Realtek\RealtekAPO_739\RealtekAPO.inf
Driver package added successfully.
Published Name:         oem22.inf

Adding driver package:  Win64\Realtek\RealtekHSA_205\RealtekHSA.inf
Driver package added successfully.
Published Name:         oem24.inf

Adding driver package:  Win64\Realtek\RealtekService_224\RealtekService.inf
Driver package added successfully.
Published Name:         oem27.inf

Total driver packages:  6
Added driver packages:  6

Done installing driver
<->
Begin force update procedure...

HDAUDIO\FUNC_01&VEN_10EC&DEV_0889&SUBSYS_1458A022&REV_1000\4&36360A8E&0&0201: Disabled
1 device(s) disabled.

No matching devices found.

Win64\Realtek\UpdatedCodec\RTAIODAT.DAT
Win64\Realtek\UpdatedCodec\RTKVHD64.sys
        2 file(s) copied.

Enabling Windows advanced startup recovery menu in case something goes very wrong...
The operation completed successfully.

HDAUDIO\FUNC_01&VEN_10EC&DEV_0889&SUBSYS_1458A022&REV_1000\4&36360A8E&0&0201: Enabled
1 device(s) are enabled.

No matching devices found.

**Comment by akks1981** [comment]
looks good! have you the Realtek Audio Console 1.9.205.0 in the Windows Store after install?

**Comment by gtumanyan** [comment]
Yes, but the driver stays the same 
![image](https://user-images.githubusercontent.com/24494814/70499438-30d40880-1b2a-11ea-821b-3bde336fdec7.png)

**Comment by akks1981** [comment]
try Windows 10 Insider Preview 19037.1

**Comment by pal1000** [comment]
I have no idea what's going on. I wonder if `Realtek Universal Audio Service`, `Hardware support application` and `Audio Effects Component` were updated. You can check with device manager under software components.

**Comment by AlyoshaVasilieva** [comment]
For me the Realtek(R) Audio driver is listed as `6.0.8844.1` with old date but RTKVHD64.sys (in its Driver Details) is shown as `6.0.8855.1`. So it seems at least that is updated correctly, and everything else (A-Volute, Audio Effects, Universal Service, HSA) shows the right date.

**Comment by gtumanyan** [comment]
Yes, now I see it 
![image](https://user-images.githubusercontent.com/24494814/70591912-dcdc2900-1be8-11ea-8196-ec6343f20bc9.png)
Was confused by "No matching devices found." message

**Comment by pal1000** [comment]
@gtumanyan, @AlyoshaVasilieva I think you still have remnants of Realtek OEM specific UAD drivers on your computers, because driver version should be 6.0.8856.1 with file version 6.0.8857.1 for @gtumanyan and 6.0.8824,1 with file version 6.0.8855.1 for @AlyoshaVasilieva; there should be no 6.0.8844.1 anywhere.
I can take a look if you 2 post screenshots from [DriverStore Explorer](https://github.com/lostindark/DriverStoreExplorer/releases).

**Comment by AlyoshaVasilieva** [comment]
@pal1000 Screenshots:

https://i.imgur.com/FLEFCcI.png (a-volute here)  
https://i.imgur.com/WPPWpm4.png  
https://i.imgur.com/rpLBY8j.png  
https://i.imgur.com/R5OiGUF.png (realtek here)

**Comment by pal1000** [comment]
@AlyoshaVasilieva I noticed you haven't removed any UAD OEM specific components before installing my generic package which can cause problems, but it looks like your sound card is supported by MSI UAD Nahimic package which is one of the 3 packages that are actively maintained with bleeding edge updates so you don't need my generic package at all, Actually Windows didn't even load it from driver store due to finding proper OEM UAD specific driver in there with better hardware ID matching.

Since your sound card is so well supported by UAD driver you just need the official MSI Nahimic package and A-Volute 3rd party extension. You'll find MSI Nahimic package on [Realtek FTP Server](ftp://ftp3.realtek.com/Realtek/)

**Comment by gtumanyan** [comment]
> post screenshots from [DriverStore Explorer]
![image](https://user-images.githubusercontent.com/24494814/70710396-23687b00-1cf0-11ea-91cf-01a91c4326f5.png)

**Comment by AlyoshaVasilieva** [comment]
@pal1000 Thanks a ton for those instructions. I'm indeed on an MSI motherboard, so I'll try that soon.

I didn't think to uninstall the standard drivers (and I think I went normal->generic->normal->generic) as I assumed the initial uninstaller of this generic package also included uninstalling that. Since the driver filenames are different it makes sense that it doesn't, but possibly would be good to note in README/setup.

**Comment by pal1000** [comment]
@AlyoshaVasilieva, I updated the readme to explain that is necessary to remove standard driver, why it's necessary and how to do it thoroughly.

**Comment by pal1000** [comment]
@gtumanyan, it looks you also have a Realtek UAD OEM specific driver in place. There is a `hdxrtgi,inf` in there that must disappear before generic driver can load.  Follow instructions from [readme](https://github.com/pal1000/Realtek-UAD-generic/blob/master/README.md#switching-from-other-realtek-hd-audio-drivers).

**Comment by gtumanyan** [comment]
I followed your instructions, the driver store now
![image](https://user-images.githubusercontent.com/24494814/70776372-efdc2e00-1d8d-11ea-9ef8-181368531fb7.png)
but Realtek Audio Console can not connect to RPC service 
![image](https://user-images.githubusercontent.com/24494814/70776427-19955500-1d8e-11ea-8135-06aca782041f.png)

**Comment by pal1000** [comment]
@gtumanyan, both previous and this screenshots are incomplete, I don't see the `Extensions` driver class in there, I only see `Software components` and `Sound, video and game controllers` driver classes. I bet there is an inf in there similar to `hdxrtgi.inf`, probably `HDX_GigabyteExt_RTK.inf` which would explain why Realtek Audio Console doesn't work. It looks like you may have failed step 7 of instructions from readme so you'll have to do over.

**Comment by gtumanyan** [comment]
Thanks a lot! I've realy missed Extensions class there. Should've got drivers sorted by provider to notice that.
Takk!
