### ISSUE TITLE
Windows Update replaces the UAD-generic driver - Howto stop?

### ISSUE THREAD

**Issue by techscgh** [pal1000/Realtek-UAD-generic#52]
Hello,
this is not an issue of the provided UAD-generic package, but rather a question howto stop Windows automatically replacing the installed UAD-generic by the "official" driver again.

Thankk you

**Comment by pal1000** [comment]
This one is tricky. There was an attempt in #45 but it didn't work well for everyone. Maybe it does for you. Even better if you are Windows pro edition or higher, because manually using Group policy is guaranteed to work, Read #45 for all details.

**Comment by techscgh** [comment]
Thank you, I'll give it a try!

**Comment by techscgh** [comment]
Given Windows 10 Pro, the only solution working on my side at present is: Group Policy "Do not include drivers with Windows Updates" ENABLED.

**Comment by moriel5** [comment]
Using the "Hide Updates" troubleshooter, I simply hide the non-generic updates.

**Comment by techscgh** [comment]
Thank you!

**Comment by moriel5** [comment]
I'm glad to be of help.

By the way, you have to be really quick with the troubleshooter, since you need to hide the update before it actually downloads, but after it gets queued.

**Comment by kiwi5** [comment]
perhaps disconnect the internet when you see the update you want to hide, before it downloads? would that work?

**Comment by pal1000** [comment]
It might, but I can't know for sure because I am not affected. In my case Windows offers a legacy Realtek HDA driver but only as an optional driver update that is never forced pushed. Also I am on Windows 10 Version 20H2.

**Comment by moriel5** [comment]
> perhaps disconnect the internet when you see the update you want to hide, before it downloads? would that work?

That wont work, since you cannot hide any updates without being online, due to the troubleshooter actually searching through Microsoft's repository.
Thus, you need to be quick about it.
First install the generic UAD drivers offline, and then do the following:
Hide as soon as you are online, then immediately go offline and stop Windows Update and BITS, wipe the Windows Update's download folder, go online, and check for updates again.

This is especially important with Dell PCs from the last ~4-5 years, since they try forcing a driver that potentially damages the hardware (by forcing it beyond it's limits, while at the same time reducing overall performance by introducing unneeded overhead).
