### ISSUE TITLE
Why the old driver 6.8924.1?

### ISSUE THREAD

**Issue by Daisenki** [pal1000/Realtek-UAD-generic#53]
Why do you still use the old 6.8924.1 from 26.03.2020 for the pack? There is a 6.0.8988.1 from 14.07.2020.

I'm using your packs now since a long time, the ASUS Realtek Audio Control shows the installed version from the pack, but use the old driver 6.8924.1, that always confuse me. Or I did something wrong, I use the setup.cmd, let the setup install and use the minimal pack when it ask me.

**Comment by Daisenki** [comment]
[6.0.8988.1.zip](https://github.com/pal1000/Realtek-UAD-generic/files/5316747/6.0.8988.1.zip)

I got these from the tool driver easy and it did update to 6.0.8988.1 on my system. I don't know if it helps you in any way, its hdxasus.inf, hdxrt.cat, rtaiodat.dat and rtkvhd64.sys

**Comment by pal1000** [comment]
No it doesn't help. I need hdxrtu.cat at minimum. hdxrt.inf and hdxrtsst.inf can be crafted through some guesswork if we are lucky.

**Comment by DealsBeam** [comment]
6.0.8960.1 is available on https://www.asus.com/Motherboards/ROG-STRIX-B450-F-GAMING-II/ driver page, not sure if that can help

**Comment by pal1000** [comment]
No, it doesn't help either.

**Comment by Daisenki** [comment]
Dammit, what's about all that drivers available at sites like station-drivers.com? 
Like "Realtek HD Audio (UAD) Drivers Version R2.8x (9030.1) WHQL (Asrock)" here https://www.station-drivers.com/index.php?option=com_remository&Itemid=352&func=fileinfo&id=4622&lang=fr-ca

**Comment by DealsBeam** [comment]
I got the latest Realtek audio driver update from https://www.snappy-driver-installer.org/download/

**Comment by pal1000** [comment]
> 
> 
> Dammit, what's about all that drivers available at sites like station-drivers.com?
> Like "Realtek HD Audio (UAD) Drivers Version R2.8x (9030.1) WHQL (Asrock)" here https://www.station-drivers.com/index.php?option=com_remository&Itemid=352&func=fileinfo&id=4622&lang=fr-ca

Those are OEM specific Realtek UAD drivers. They only support specific PC brands and models each.
This project aims to get HDA FF00 compatible systems to use UAD.

**Comment by epman100** [comment]
@Daisenki & @pal1000

the **hdxrtu.cat** signature file is created by Microsoft.  Realtek has to pay money to Microsoft for them to make that hdxrtu.cat file if Realtek decides to submit newer HDXRT.inf & HDXRTSST.inf files but it looks like Realtek has cut back on production costs and not produce newe rHDXRT.inf & HDXRTSST.inf files mostly because of the current pandemic health situation and that caused many global economies to go down.

you guys need to understand the current world situation we're living in.

until this global pandemic world crisis ends and global economies recover (which may take many months or a few years), it looks like Realtek won't be making any newer HDXRT.inf & HDXRTSST.inf files and thus Microsoft can not make a newer HDXRTU.cat file.

the last version that had those generic HDXRT.inf & HDXRTSST.inf files along with the **hdxrtu.cat** file was [v6.0.8904.1](https://www.catalog.update.microsoft.com/Search.aspx?q=6.0.8904.1) from MS Update.  the [v6.0.8924.2](https://www.catalog.update.microsoft.com/Search.aspx?q=6.0.8924.2) driver from MS Update did include the hdxrtu.cat signature file but left out the generic HDXRT.inf & HDXRTSST.inf files.

unless there's another new "point 2" (aka .2) UAD driver release on MS Update that may include a hdxrtu.cat file higher than 8924.2 (and those releases are kinda rare), I just don't see Realtek making anymore new UAD drivers with the hdxrtu.cat file included.
