### ISSUE TITLE
How to set/change default audio output device

### ISSUE THREAD

**Issue by Osahashi** [pal1000/Realtek-UAD-generic#56]
Maybe someone can help me with my problem, Windows use "Standard" as default output device for every new sound source, the sound output in general works with that yes, but chancing it to the real device, in my case "Realtek Digital Output" the sound is better, something is different, but don't ask me what.
The problem is, I need to switch the device for every program/game by hand and it is only showing when it runs. Really annoying and every time I update the driver all is again wrong for me.

Is there maybe any way to chance the default at Windows 10, at the registry? 

![Sound](https://user-images.githubusercontent.com/22057956/96441844-795c5800-120a-11eb-9918-26e381204e82.JPG)

**Comment by pal1000** [comment]
Try Settings - Sounds - Manage sound devices then disable that audio device you don't like.

**Comment by Daisenki** [comment]
I have all audio devices deactivated, except the Realtek Digital Output what I want for everything. 

![Sound2](https://user-images.githubusercontent.com/22057956/96564471-7ec9a900-12c3-11eb-99ec-2a8d34a06f97.JPG)
![Sound3](https://user-images.githubusercontent.com/22057956/96564473-7f623f80-12c3-11eb-82de-09954367583f.JPG)
![Sound4](https://user-images.githubusercontent.com/22057956/96564475-7f623f80-12c3-11eb-8aaa-2d2240ca83af.JPG)

In the device manager is the Realtek(R) Audio and the Realtek Digital Output (Realtek(R) Audio), maybe it's because of the different driver: 
![Sound5](https://user-images.githubusercontent.com/22057956/96565484-b2590300-12c4-11eb-99b2-d76f7799f6a1.JPG)

sorry for my Windows text, it's German

**Comment by high1** [comment]
You will always get default or standard in German for each app, unless you change it by hand. This is Windows behavior, not something a driver can - or should - deal with.
