### ISSUE TITLE
Two installs needed

### ISSUE THREAD

**Issue by DooGie666** [pal1000/Realtek-UAD-generic#7]
Whn first running setup.cmd the existing Realtek driver is not removed so the new driver can't be installed. However if I then run setup.cmd for a second time the process works perfectly.

**Comment by pal1000** [comment]
The 1st run of setup.cmd takes down Realtek Universal Audio Service, creates a startup entry to automatically engage the 2nd run and then logs you out so that the uninstall that happens on 2nd run completes without having to reboot afterwards.
The 2nd run happens automatically as you log back in. If it doesn't, just let me know,

So to answer your connection setup.cmd is supposed to run 2 times, though the 2nd one should be automatic unless you do something unexpected like closing cmd window instead of pressing any to continue when prompted.

**Comment by shibajee** [comment]
isn't it better to create 2 separate .cmd/.bat file like install.cmd and uninstall.cmd ?

**Comment by pal1000** [comment]
You are asked if you want to install after uninstall finishes so it is possible to uninstall only so I don't see any problem in the current monolithic setup design.

**Comment by pal1000** [comment]
This was fixed by #18.
